// generator for chi_squared_quantile_table_0_95.h -- run against the SAME boost the
// estimator used at runtime so the baked values are bit-identical to what it computed
#include <boost/math/distributions/chi_squared.hpp>
#include <cstdio>
int main() {
  printf("// AUTO-GENERATED by tools/gen_chi2_table (boost::math %d.%d.%d quantiles at p=0.95)\n",
         BOOST_VERSION / 100000, (BOOST_VERSION / 100) % 1000, BOOST_VERSION % 100);
  printf("// dof 1..4095; entry [0] is a poison NaN (dof 0 is meaningless)\n");
  printf("static const double CHI2_QUANTILE_0_95[4096] = {\n");
  printf("    0.0/0.0,\n");
  for (int i = 1; i < 4096; i++) {
    boost::math::chi_squared d(i);
    printf("    %.17g,%s", boost::math::quantile(d, 0.95), (i % 4 == 0) ? "\n" : " ");
  }
  printf("\n};\n");
  return 0;
}
